### ISSUE TITLE
the package version

### ISSUE THREAD

**Issue by li-car-fei** [mazzzystar/teach-show-consult#1]
can you provide the package versions?

**Comment by li-car-fei** [comment]
> @li-car-fei Hi I've changed the packages in `requirements.txt` with a specified version.

when i run the consult.py, i got this error:
```
TypeError: search() missing 3 required positional arguments: 'k', 'distances', and 'labels'
```

**Comment by mazzzystar** [comment]
Could you provide the full error log? I can't see the search function.

**Comment by li-car-fei** [comment]
> Could you provide the full error log? I can't see the search function.

here is the full error log:

```
Let's consult the music master!
You:
c d8 > g
Traceback (most recent call last):
  File "/Users/skyworthclub/Documents/carfied/music-transformer-srp-2022/teach-show-consult/consult.py", line 50, in <module>
    result = qa_chain({"question": question, "chat_history": chat_history})
  File "/opt/anaconda3/envs/teach-show-consult/lib/python3.9/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/opt/anaconda3/envs/teach-show-consult/lib/python3.9/site-packages/langchain/chains/base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "/opt/anaconda3/envs/teach-show-consult/lib/python3.9/site-packages/langchain/chains/chat_vector_db/base.py", line 92, in _call
    docs = self.vectorstore.similarity_search(
  File "/opt/anaconda3/envs/teach-show-consult/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 166, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k)
  File "/opt/anaconda3/envs/teach-show-consult/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 136, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(embedding, k)
  File "/opt/anaconda3/envs/teach-show-consult/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 110, in similarity_search_with_score_by_vector
    scores, indices = self.index.search(np.array([embedding], dtype=np.float32), k)
TypeError: search() missing 3 required positional arguments: 'k', 'distances', and 'labels'

```

**Comment by mazzzystar** [comment]
I'm not sure your `faiss` version, It seems`index.search` only has two arguments as the langchain doc shows: https://python.langchain.com/en/latest/_modules/langchain/vectorstores/faiss.html#FAISS.similarity_search_with_score_by_vector
